/* Generated By:JJTree: Do not edit this line. ASTDeclareStmt.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package analyzer.ast;

public
class ASTDeclareStmt extends SimpleNode {
  public ASTDeclareStmt(int id) {
    super(id);
  }

  public ASTDeclareStmt(Parser p, int id) {
    super(p, id);
  }

    /** Accept the visitor. **/
    public Object jjtAccept(ParserVisitor visitor, Object data) {
        return visitor.visit(this, data);
    }

    // PLB
    private String m_value = null;
    public void setValue(String v) { m_value = v; }
    public String getValue() { return m_value; }
}
/* JavaCC - OriginalChecksum=85fee3acb100ae565bcf1d9261f781f5 (do not edit this line) */
