/* Generated By:JJTree: Do not edit this line. ASTRealValue.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package analyzer.ast;

public
class ASTRealValue extends SimpleNode {
  public ASTRealValue(int id) {
    super(id);
  }

  public ASTRealValue(Parser p, int id) {
    super(p, id);
  }


    /** Accept the visitor. **/
    public Object jjtAccept(ParserVisitor visitor, Object data) {
        return visitor.visit(this, data);
    }

    // PLB
    private float m_value = 0;
    public void setValue(float v) { m_value = v; }
    public float getValue() { return m_value; }
}
/* JavaCC - OriginalChecksum=4c615a376e751c2202821f7b2e5e426d (do not edit this line) */
